# Generated by Django 6.0.7 on 2026-07-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='empleado',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
